version: "3.3"
services:
  manager:
    container_name: wazuh-manager
    build: ./wazuh-manager/.
    restart: always
    ports:
      - "55000:55000"
  agente:
    container_name: wazuh-agente
    build: ./wazuh-agente/.
    restart: always