version: '3.4'

services:
  mongo:
    image: mongo
    environment:
      MONGODB_USER: miso
      MONGODB_PASS: miso
      MONGODB_DATABASE: miso
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"
  spring-web-mongo:
    build: .
    ports:
      - 80:8080
    depends_on:
      - mongo